---

- name: dotfiles | Check if dotfiles dir created
  ansible.builtin.stat:
    path: ~/dotfiles
  register: dotfiles

- name: dotfiles | Cloning dotfiles
  git: 
    repo: git@github.com:david-abarca/dotfiles.git
    dest: ~/dotfiles
  when: dotfiles.stat.isdir is not defined

- name: dotfiles | Delete default zshrc
  file:
    path: ~/.zshrc
    state: absent
  when: dotfiles.stat.isdir is not defined

- name: dotfiles | Creating symlinks for dotfiles
  shell: stow --verbose tmux vimrc zsh
  args:
    chdir: ~/dotfiles
  when: dotfiles.stat.isdir is not defined
