---

- name: RedHat | Add new admin user
  become: true
  user:
    name: '{{ admin_username }}'
    groups: wheel
    # Disable user password (only use SSH)
    password: '!'
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519

- name: RedHat | Create .ansible/tmp for new admin
  become: true
  file:
    path: /home/{{ admin_username }}/.ansible/tmp
    state: directory
    mode: '0700'
    owner: "{{ admin_username }}"
    group: wheel
