---

- name: Shared | Add admin user to own sudoers.d path
  become: true
  lineinfile:
    path: '/etc/sudoers.d/{{ admin_username }}'
    line: '{{ admin_username }}        ALL=(ALL)       NOPASSWD: ALL'
    state: present
    insertafter: EOF
    validate: "visudo -cf %s"
    create: true
