---

- name: RedHat | Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: RedHat | Allow SSH in firewalld
  ansible.posix.firewalld:
    port: '22/tcp'
    state: enabled
    permanent: true

- name: RedHat | Enable loggin of denied traffic
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^LogDenied'
    line: LogDenied=all
  notify: Restart firewalld
