---

- name: Shared | Journalctl storage=persistent
  become: true
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#Storage=auto'
    line: Storage=persistent
  notify:
  - Restart systemd-journald

- name: Shared | Journalctl persistent boot
  become: true
  file:
    path: /var/log/journal
    state: directory
  notify:
  - Restart systemd-journald
