---

- name: RedHat | Install DNF
  become: true
  yum:
    name: dnf
    state: latest
  when: ansible_distribution_major_version < '8'

- name: RedHat | Update cache and upgrade packages
  become: true
  dnf:
    name: "*"
    update_cache: true
    state: latest

- name: RedHat | Install shared software
  become: true
  dnf:
    name: '{{ packages_shared }}'
    state: latest

- name: Debian | Install distribution family software
  become: true
  dnf:
    name: '{{ packages_dnf }}'
    state: latest

- name: RedHat |  Install EPEL separate (CentOS only)
  become: true
  dnf:
    name: epel-release
    state: latest
  when: ansible_distribution|lower == 'centos'
