---

- name: Debian | Update all packages
  become: true
  apt:
    update_cache: true 
    force_apt_get: true

- name: Debian | Upgrade all packages
  become: true
  apt:
    upgrade: dist
    force_apt_get: true

# - name: Debian | Check if a reboot is needed for Debian and Ubuntu boxes
#   register: reboot_required_file
#   stat:
#     path: /var/run/reboot-required
#     get_md5: no

# - name: Reboot the Debian or Ubuntu server
#   reboot:
#     msg: "Reboot initiated by Ansible due to kernel updates"
#     connect_timeout: 5
#     reboot_timeout: 300
#     pre_reboot_delay: 0
#     post_reboot_delay: 30
#     test_command: uptime
#   when: reboot_required_file.stat.exists

- name: Debian | Install shared software
  become: true
  apt:
    name: '{{ packages_shared }}'
    state: latest

- name: Debian | Install distribution family software
  become: true
  apt:
    name: '{{ packages_apt }}'
    state: latest

- name: Debian | Check for latest duf
  uri:
    url: https://api.github.com/repos/muesli/duf/releases/latest
    return_content: true
  register: duf_latest

- name: Debian | Install duf trough apt
  become: true
  apt:
    deb: "{{ item.browser_download_url }}"
  loop: "{{ duf_latest.json.assets }}"
  loop_control:
    label: "{{ item.name }}"
  when: "'linux_amd64.deb' in item.name"
