---

- name: Shared | Check for latest exa
  uri:
    url: https://api.github.com/repos/ogham/exa/releases/latest
    return_content: true
  register: exa_latest

- name: Shared | Download and unpack exa
  become: true
  unarchive:
    src: "{{ item.browser_download_url }}"
    remote_src: true
    dest: /tmp/
  loop: "{{ exa_latest.json.assets }}"
  loop_control:
    label: "{{ item.name }}"
  when: "'exa-linux-x86_64' in item.name"
  changed_when: false

- name: Shared | Copy exa binary
  become: true
  copy:
    src: /tmp/exa-linux-x86_64
    remote_src: true
    dest: /usr/bin/exa
    mode: '0755'

- name: Shared | Cleanup exa download
  file:
    path: /tmp/exa-linux-x86_64
    state: absent
  changed_when: false

- name: Shared | Download prettyping
  become: true
  get_url:
    url: https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
    dest: /usr/bin/
    mode: '0755'
