---

- name: Shared | Download and unpack exa
  become: true
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    remote_src: true
    dest: /tmp/

- name: Shared | Copy exa binary
  become: true
  copy:
    src: /tmp/exa-linux-x86_64
    remote_src: true
    dest: /usr/bin/exa
    mode: '0755'

- name: Shared | Cleanup exa download
  file:
    path: /usr/bin/exa-linux-x86_64
    state: absent

- name: Shared | Download prettyping
  become: true
  get_url:
    url: https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
    dest: /usr/bin/
    mode: '0755'
